general:
  indices_param: [1, 3]  # Indices to parameters we want to use
  model_datasizes: [100, 500] #, 1000, 2000, 3000, 4000, 5000, 6000]  # Number of training samples
  num_nn: [1, 10, 30]
prediction_time_exp:
  test_data_sizes: [400, 800, 1200, 1600, 2000, 2400, 2800]
  test_data_filename: 'TsData'
  model_datasize: 6000
files:
  model_folder: 'Results/trained_models'
  results_folder: 'Results/predictions'
  test_data_folder: 'Data/BeelerReuter_idx'
  test_data_filenames: 'TsData'
  data_folder: 'Data/BeelerReuter_idx'
  trdata_filename: 'TrData_N'