### This is the configuration file for the training of the algorithms
files:
  data_folder: 'Data/BeelerReuter_idx'
  trdata_filename: 'TrData_N'
  results_folder: 'Results/trained_models'
falkon:
  bw_grid: [4, 1, 20]  # Bw grid info [min, max, num_samples]
knn:
  number_of_nn: [1, 10, 20, 50]  # Number of nearest neighbours
general:
  indices_param: [1, 3]  # Indices to parameters we want to use
  training_data_sizes: [100, 500, 1000, 2000, 3000, 4000, 5000, 6000]  # Number of training samples